"""Initial migration

Revision ID: f34631059dba
Revises: 
Create Date: 2025-12-20 10:53:57.225352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34631059dba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('query_input', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_logs_id'), 'weather_logs', ['id'], unique=False)
    op.create_index(op.f('ix_weather_logs_query_input'), 'weather_logs', ['query_input'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_logs_query_input'), table_name='weather_logs')
    op.drop_index(op.f('ix_weather_logs_id'), table_name='weather_logs')
    op.drop_table('weather_logs')
    # ### end Alembic commands ###
